version: '3.4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./packages/public/server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  hydra:
    image: oryd/hydra:v1.4.2
    ports:
      - '4444:4444'
      - '4445:4445'
    command: serve all --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://de.serlo.localhost:4567/auth/hydra/login
      - URLS_CONSENT=http://de.serlo.localhost:4567/auth/hydra/consent
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis

  #  editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/editor-renderer/Dockerfile
  editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-editor-renderer

  #  legacy-editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/legacy-editor-renderer/Dockerfile
  legacy-editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-legacy-editor-renderer

  server-composer:
    image: composer:1.8
    volumes:
      - ./packages/public/server/composer.json:/app/composer.json:cached
      - ./packages/public/server/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/src/module:/app/src/module:cached
      - ./packages/public/server/src/vendor:/app/src/vendor:cached

  server-composer-dev-tools:
    image: composer:1.8
    volumes:
      - ./packages/public/server/dev-tools/composer.json:/app/composer.json:cached
      - ./packages/public/server/dev-tools/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/dev-tools/vendor:/app/vendor:cached

  server-httpd:
    build:
      context: packages/public/server
      dockerfile: docker/httpd/Dockerfile
      target: base
    ports:
      - '4567:80'
    volumes:
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
    environment:
      - PHP_HOST=server-php

  server-php:
    build:
      context: packages/public/server
      dockerfile: docker/php/Dockerfile
      target: base
    volumes:
      - ./packages/public/server/dev-tools/vendor:/usr/local/apache2/htdocs/dev-tools/vendor:delegated
      - ./packages/public/server/package.json:/usr/local/apache2/htdocs/package.json:delegated
      - ./packages/public/server/php-cs-fixer.config.php:/usr/local/apache2/htdocs/php-cs-fixer.config.php:delegated
      - ./packages/public/server/phpunit.xml:/usr/local/apache2/htdocs/phpunit.xml:delegated
      - ./packages/public/server/src/config:/usr/local/apache2/htdocs/src/config:delegated
      - ./packages/public/server/src/lang:/usr/local/apache2/htdocs/src/lang:delegated
      - ./packages/public/server/src/module:/usr/local/apache2/htdocs/src/module:delegated
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
      - ./packages/public/server/src/test:/usr/local/apache2/htdocs/src/test:delegated
      - ./packages/public/server/src/vendor:/usr/local/apache2/htdocs/src/vendor:delegated
      - ./packages/public/server/src/init_autoloader.php:/usr/local/apache2/htdocs/src/init_autoloader.php:delegated

  server-migrate:
    build:
      context: packages/public/server
      dockerfile: docker/migrate/Dockerfile
    volumes:
      - ./packages/public/server/migrations:/usr/src/app/migrations:delegated
    environment:
      - DATABASE=mysql://root:secret@mysql:3306/serlo?query

  static-assets:
    image: nginx
    ports:
      - '8082:80'
    volumes:
      - ./packages/public/static-assets/src:/usr/share/nginx/html:delegated
