version: '3.4'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./packages/public/server/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret

  redis:
    image: redis:5.0

  hydra:
    image: oryd/hydra:v1.2.3
    ports:
      - '4444:4444'
      - '4445:4445'
    command: serve all --dangerous-force-http
    environment:
      - LOG_LEVEL=debug
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - URLS_SELF_ISSUER=http://localhost:4444
      - URLS_LOGIN=http://de.serlo.localhost:4567/auth/hydra/login
      - URLS_CONSENT=http://de.serlo.localhost:4567/auth/hydra/consent
      - DSN=memory
      - SECRETS_SYSTEM=youReallyNeedToChangeThis
      - OIDC_SUBJECT_IDENTIFIERS_ENABLED=public,pairwise
      - OIDC_SUBJECT_IDENTIFIERS_PAIRWISE_SALT=youReallyNeedToChangeThis

  #  editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/editor-renderer/Dockerfile
  editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-editor-renderer

  frontend:
    build:
      context: .
      dockerfile: packages/public/frontend/docker/Dockerfile
      target: development
    ports:
      - '3000:3000'

  frontend-assets:
    image: nginx
    ports:
      - '3001:80'
    volumes:
      - ./packages/public/frontend/public:/usr/share/nginx/html:delegated
      - ./packages/public/frontend/docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated

  #  legacy-editor-renderer:
  #    build:
  #      context: .
  #      dockerfile: packages/public/legacy-editor-renderer/Dockerfile
  legacy-editor-renderer:
    image: eu.gcr.io/serlo-shared/serlo-org-legacy-editor-renderer

  server-composer:
    image: composer:1.8
    volumes:
      - ./packages/public/server/composer.json:/app/composer.json:cached
      - ./packages/public/server/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/src/vendor:/app/src/vendor:cached

  server-composer-dev-tools:
    image: composer:1.8
    volumes:
      - ./packages/public/server/dev-tools/composer.json:/app/composer.json:cached
      - ./packages/public/server/dev-tools/composer.lock:/app/composer.lock:cached
      - ./packages/public/server/dev-tools/vendor:/app/vendor:cached

  server-httpd:
    build:
      context: packages/public/server
      dockerfile: docker/httpd/Dockerfile
      target: base
    ports:
      - '4567:80'
    volumes:
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
    environment:
      - PHP_HOST=server-php

  server-php:
    build:
      context: packages/public/server
      dockerfile: docker/php/Dockerfile
      target: base
    volumes:
      - ./packages/public/server/dev-tools/vendor:/usr/local/apache2/htdocs/dev-tools/vendor:delegated
      - ./packages/public/server/package.json:/usr/local/apache2/htdocs/package.json:delegated
      - ./packages/public/server/php-cs-fixer.config.php:/usr/local/apache2/htdocs/php-cs-fixer.config.php:delegated
      - ./packages/public/server/phpunit.xml:/usr/local/apache2/htdocs/phpunit.xml:delegated
      - ./packages/public/server/src/config:/usr/local/apache2/htdocs/src/config:delegated
      - ./packages/public/server/src/lang:/usr/local/apache2/htdocs/src/lang:delegated
      - ./packages/public/server/src/module:/usr/local/apache2/htdocs/src/module:delegated
      - ./packages/public/server/src/public:/usr/local/apache2/htdocs/src/public:delegated
      - ./packages/public/server/src/test:/usr/local/apache2/htdocs/src/test:delegated
      - ./packages/public/server/src/vendor:/usr/local/apache2/htdocs/src/vendor:delegated
      - ./packages/public/server/src/init_autoloader.php:/usr/local/apache2/htdocs/src/init_autoloader.php:delegated

  server-migrate:
    build:
      context: packages/public/server
      dockerfile: docker/migrate/Dockerfile
    volumes:
      - ./packages/public/server/migrations:/app/migrations:delegated
    environment:
      - DATABASE=mysql://root:secret@tcp(mysql:3306)/serlo?query

  static-assets:
    image: nginx
    ports:
      - '8082:80'
    volumes:
      - ./packages/public/static-assets/src:/usr/share/nginx/html:delegated

  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:5.2.1
    depends_on:
      - zookeeper
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: 'http://0.0.0.0:8081'
  kafka-rest-proxy:
    image: confluentinc/cp-kafka-rest:5.3.1
    environment:
      KAFKA_REST_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KAFKA_REST_HOST_NAME: kafka-rest-proxy
      KAFKA_REST_DEBUG: 'true'
    depends_on:
      - schema-registry
      - zookeeper
